services:
  nacos1:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos1
    environment:
      - PREFER_HOST_MODE=ip
      - TZ=Asia/Shanghai
      - SPRING.DATASOURCE.PLATFORM=mysql
      - MODE=cluster
      - MYSQL_SERVICE_HOST=10.147.221.138
      - MYSQL_SERVICE_PORT=33061
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=12345678
      - MYSQL_SERVICE_DB_NAME=nacos
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - NACOS_AUTH_TOKEN=SecretKey01234567890123456789012345345678999987654901234567890123456789
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
    volumes:
      - ./docker/nacos1/logs:/home/nacos/logs
    ports:
      - "7777:8848"
      - "8777:9848"
      - "8778:9849"
  nacos2:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos2
    environment:
      - PREFER_HOST_MODE=ip
      - TZ=Asia/Shanghai
      - SPRING.DATASOURCE.PLATFORM=mysql
      - MODE=cluster
      - MYSQL_SERVICE_HOST=10.147.221.138
      - MYSQL_SERVICE_PORT=33061
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=12345678
      - MYSQL_SERVICE_DB_NAME=nacos
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - NACOS_AUTH_TOKEN=SecretKey01234567890123456789012345345678999987654901234567890123456789
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
    volumes:
      - ./docker/nacos2/logs:/home/nacos/logs
    ports:
      - "8888:8848"
      - "9888:9848"
      - "9889:9849"
  nacos3:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos3
    environment:
      - PREFER_HOST_MODE=ip
      - TZ=Asia/Shanghai
      - SPRING.DATASOURCE.PLATFORM=mysql
      - MODE=cluster
      - MYSQL_SERVICE_HOST=10.147.221.138
      - MYSQL_SERVICE_PORT=33061
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=12345678
      - MYSQL_SERVICE_DB_NAME=nacos
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - NACOS_AUTH_TOKEN=SecretKey01234567890123456789012345345678999987654901234567890123456789
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
    volumes:
      - ./docker/nacos3/logs:/home/nacos/logs
    ports:
      - "9999:8848"
      - "10999:9848"
      - "11000:9849"
