spring:
  profiles:
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:7777,127.0.0.1:8888,127.0.0.1:9999
    gateway:
      default-filters:
        - CircuitBreaker=default-circuit-breaker
        - RequestRateLimiter=default-rate-limiter
  main:
    web-application-type: reactive
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 200
  data:
    redis:
      sentinel:
        password: 12345678
        master: mymaster
        nodes:
          - 127.0.0.1:26379
          - 127.0.0.1:26380
          - 127.0.0.1:26381
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
      password: 12345678

# Resilience4j Circuit Breaker配置
resilience4j:
  circuitbreaker:
    instances:
      backendA:
        failure-rate-threshold: 30
        sliding-window-type: TIME_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 5s

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,gateway
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true



server:
  port: 80