spring:
  application:
    name: cart-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:7777,127.0.0.1:8888,127.0.0.1:9999
  datasource:
    url: jdbc:mysql://localhost:33070/elm_db
    username: root
    password: root
#    url: jdbc:mysql://localhost:33061/elm_springcloud
#    username: root
#    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 15000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false