spring:
  application:
    name: food-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:7777,127.0.0.1:8888,127.0.0.1:9999
    openfeign:
      circuitbreaker:
        enabled: off
  datasource:
    url: jdbc:mysql://localhost:33070/elm_db
    username: root
    password: root
#    url: jdbc:mysql://localhost:33061/elm_springcloud
#    username: root
#    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai

server:
  port: 13000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false